server:
  port: 8888

spring:
  application:
    name: springCloudConfigServer
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPOSITORY}
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
